import { ApplicationRef, PlatformRef } from '@angular/core';
export { WORKER_SCRIPT, WORKER_RENDER_PLATFORM_PROVIDERS, initializeGenericWorkerRenderer, WORKER_RENDER_APPLICATION_COMMON_PROVIDERS } from './webworker/worker_render_common';
export { WORKER_RENDER_APPLICATION_PROVIDERS, WORKER_RENDER_STARTABLE_MESSAGING_SERVICE, WebWorkerInstance } from './webworker/worker_render';
export { ClientMessageBroker, ClientMessageBrokerFactory, FnArg, UiArguments } from './web_workers/shared/client_message_broker';
export { ReceivedMessage, ServiceMessageBroker, ServiceMessageBrokerFactory } from './web_workers/shared/service_message_broker';
export { PRIMITIVE } from './web_workers/shared/serializer';
export * from './web_workers/shared/message_bus';
export { WORKER_RENDER_LOCATION_PROVIDERS } from '../src/web_workers/ui/location_providers';
export declare function workerRenderPlatform(): PlatformRef;
export declare function bootstrapStaticRender(workerScriptUri: string, customProviders?: Array<any>): Promise<ApplicationRef>;
