import { PlatformRef, Type, ComponentRef } from '@angular/core';
export { WORKER_APP_PLATFORM_PROVIDERS, WORKER_APP_APPLICATION_COMMON_PROVIDERS } from './webworker/worker_app_common';
export { WORKER_APP_APPLICATION_PROVIDERS } from './webworker/worker_app';
export { ClientMessageBroker, ClientMessageBrokerFactory, FnArg, UiArguments } from './web_workers/shared/client_message_broker';
export { ReceivedMessage, ServiceMessageBroker, ServiceMessageBrokerFactory } from './web_workers/shared/service_message_broker';
export { PRIMITIVE } from './web_workers/shared/serializer';
export * from './web_workers/shared/message_bus';
export { WORKER_APP_LOCATION_PROVIDERS } from './web_workers/worker/location_providers';
export declare function workerAppPlatform(): PlatformRef;
export declare function bootstrapStaticApp(appComponentType: Type, customProviders?: Array<any>): Promise<ComponentRef<any>>;
